FROM php:8.1-cli

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && \
    apt-get install zip unzip && \
    rm -rf /var/lib/apt/lists/* \

WORKDIR /usr/src/myapp